### ISSUE TITLE
Repositories not being Generated

### ISSUE THREAD

**Issue by MagicMilly** [taylorjayoung/RepoSweeper#16]
Hi! I was so excited to find this app as a fellow Flatiron alum. I followed the directions from your Medium [article](https://medium.com/@taylorjayoung/the-easiest-way-to-delete-multiple-github-repositories-at-once-e71e16734b59) but got stuck on Step 8 `Generate Repositories`. I did not see these words - only an image of a folder - and nothing seemed to happen when I clicked that button. 

Thank you for making this app - I'm looking forward to using it!

**Comment by taylorjayoung** [comment]
Thanks for opening up an issue! I was making some updates around that time. The web app is up an running now. If you see any more problems and want to contribute feel free to make a pull request. I am about to create some issues of my own and am looking for contributors.
