### ISSUE TITLE
What's to be deleted?

### ISSUE THREAD

**Issue by tcurdt** [taylorjayoung/RepoSweeper#4]
I wanted to scream "hurray" when I found the project - but I just don't understand the UI.

What defines what repos will be deleted? There are sections and checkboxes.
What kind of call to action is "Want only forked repos / Reset".
When a repo is in "Repos To Delete" and you set the "Delete" checkbox gets removed from the section.

I don't get it.

**Comment by tanrobotix** [comment]
Just want to scream "F*ck", the UI said that "REPO TO DELETE", I checked it, and the repos that I want to delete is not delete, it DELETE THE RPO I DON'T WANT TO DELETE.

**Comment by tcurdt** [comment]
I am so glad I didn't try it. So sorry, @tanrobotix

**Comment by taylorjayoung** [comment]
Sorry about the confusion. It was really poorly designed by me. I made a bunch of changes to prevent that form happening including more clear verbiage and a confirmation screen. If you ever feel like giving it a shot or contributing let me know.
